language: java
jdk:
- oraclejdk7
branches:
  except:
  - /^(?i:wip).*$/
sudo: false
before_install:
  - pip install --user codecov
after_success:
  - .config/deploy-artifacts.sh
  - .config/publish-javadocs.sh
  - codecov