<div id="footer">
<!--Generated by <a href="http://code.google.com/p/doclava/">Doclava</a>-->
Copyrigth &copy Centro de Investigación en Tecnoloxías da Información (<a href="http://citius.usc.es">CITIUS</a>).
</div> <!-- end footer -->
